In [28]:
import pandas as pd
import requests
import zipfile

In [12]:
df = pd.read_csv('/Users/darrenfishell/Downloads/indiv20/itcont.txt',sep='|',error_bad_lines=False)
#df = pd.read_csv('/../../../..Downloads/indiv20/by_date/itcont_2020_20190629_20190911.txt')

b'Skipping line 4209545: expected 21 fields, saw 26\n'
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (3,5,10,11,12,15,16,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [29]:
r = requests.get('https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/2020/indiv20.zip')

In [ ]:
zf = zipfile.ZipFile(r.content)

In [ ]:
df_web = pd.read_csv(zf.open('itcont.txt',sep='|',error_bad_lines=False))
r.content

In [13]:
df.head(10)

,C00432906,T,TER,P,201901219143901218,22Y,IND,"LEMUNYON, GLENN",WASHINGTON,DC,...,Unnamed: 11,Unnamed: 12,01182019,500,Unnamed: 15,SB20A.55756,1305860,Unnamed: 18,Unnamed: 19,4021320191639407455
0,C00432906,T,TER,P,201901219143901218,22Y,IND,"LEMUNYON, GLENN",WASHINGTON,DC,...,NaN,NaN,1182019.0,-500,NaN,SB20A.55755,1305860,NaN,NaN,4021320191639407453
1,C00638478,T,TER,P,201901289144040159,15C,CAN,"JANOWICZ, PHILIP",BUENA PARK,CA,...,FRIENDS OF PHIL JANOWICZ,CANDIDATE,1282019.0,35000,H8CA39133,3703295,1307800,NaN,CONVERTING PRIMARY LOAN TO CONTRIBUTION,4021220191639267648
2,C00640870,T,TER,P,201901259144002482,15C,CAN,"RICHARDSON, CHARDO",LONGWOOD,FL,...,INFORMATION REQUESTED,INFORMATION REQUESTED,1242019.0,76,H8FL07054,VTQYWHKD8W6,1307204,NaN,CONTRIBUTION FOR DEBT RETIREMENT,4021320191639532337
3,C00638478,T,TER,P,201901289144040158,15,IND,"STEVENS, RICHARD",DIAMOND BAR,CA,...,NOT EMPLOYED,NOT EMPLOYED,1252019.0,-50,NaN,3703278,1307800,NaN,CHECK LOST,4021220191639267645
4,C00638478,T,TER,P,201901289144040159,15C,CAN,"JANOWICZ, PHILIP",BUENA PARK,CA,...,FRIENDS OF PHIL JANOWICZ,CANDIDATE,1282019.0,59816,H8CA39133,3703293,1307800,NaN,CONVERTING PRIMARY LOAN TO CONTRIBUTION,4021220191639267646
5,C00638478,T,TER,P,201901289144040159,15C,CAN,"JANOWICZ, PHILIP",BUENA PARK,CA,...,FRIENDS OF PHIL JANOWICZ,CANDIDATE,1282019.0,50000,H8CA39133,3703294,1307800,NaN,CONVERTING PRIMARY LOAN TO CONTRIBUTION,4021220191639267647
6,C00638478,T,TER,P,201901289144040160,15C,CAN,"JANOWICZ, PHILIP",BUENA PARK,CA,...,FRIENDS OF PHIL JANOWICZ,CANDIDATE,1282019.0,33000,H8CA39133,3703296,1307800,NaN,CONVERTING PRIMARY LOAN TO CONTRIBUTION,4021220191639267649
7,C00104885,A,TER,P,201901289144031509,15,IND,"VOCKE, MONIQUE S",METAIRIE,LA,...,CB&I PSG,V.P. HUMAN RESOURCES,12312018.0,15,NaN,SA11AI.17749,1307636,NaN,NaN,4022220191643530656
8,C00104885,A,TER,P,201901289144031508,15,IND,"CHAVOUS, HENRY B",EVANS,GA,...,CB&I PROJECT SERVICES GROUP,V.P. PROJECT SUPPORT,12312018.0,20,NaN,SA11AI.17744,1307636,NaN,NaN,4022220191643530652
9,C00104885,A,TER,P,201901289144031508,15,IND,"KEELER, RAYMOND J",MARTINEZ,GA,...,CB&I PSG,PROJECT MANAGER,12312018.0,25,NaN,SA11AI.17746,1307636,NaN,NaN,4022220191643530653